name: Go
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Verify Vendoring
        run: make verify-vendor
      - name: Verify Generated Code
        run: make verify-generate
      - name: Build
        run: make build
      - name: Test
        run: make test
